/**
 * ELEMENT 118 — AUTHORITATIVE 118-ELEMENT SCIENTIFIC DATASET
 * Sources: IUPAC, NIST Standard Reference Database, Royal Society of Chemistry.
 * Scientifically verified data. Missing/synthetic properties explicitly labeled "Data not available".
 */

const ELEMENTS_DATA = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: "1.008 u",
    electronicConfiguration: "1s¹",
    electronShells: [1],
    valenceElectrons: 1,
    group: 1,
    period: 1,
    block: "s",
    category: "reactive-nonmetal",
    state: "Gas",
    protons: 1,
    neutrons: 0,
    electrons: 1,
    meltingPoint: "13.99 K (-259.16 °C)",
    boilingPoint: "20.27 K (-252.88 °C)",
    density: "0.08988 g/L",
    electronegativity: 2.20,
    oxidationStates: "+1, -1",
    discoveryYear: 1766,
    discoveredBy: "Henry Cavendish",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Rocket fuel", "Ammonia synthesis for fertilizers", "Hydrogen fuel cells", "Petroleum refining"],
    funFacts: [
      "Hydrogen is the most abundant chemical element in the universe, constituting roughly 75% of all baryonic mass.",
      "It is the only element whose most common isotope (Protium) contains no neutrons in its nucleus."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Standard atomic weight is an interval; conventional value is 1.008 u."
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: "4.0026 u",
    electronicConfiguration: "1s²",
    electronShells: [2],
    valenceElectrons: 2,
    group: 18,
    period: 1,
    block: "s",
    category: "noble-gas",
    state: "Gas",
    protons: 2,
    neutrons: 2,
    electrons: 2,
    meltingPoint: "0.95 K (-272.2 °C, at 2.5 MPa)",
    boilingPoint: "4.22 K (-268.93 °C)",
    density: "0.1786 g/L",
    electronegativity: "Data not available",
    oxidationStates: "0",
    discoveryYear: 1868,
    discoveredBy: "Pierre Janssen, Norman Lockyer",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Cryogenics (cooling MRI magnets)", "Deep-sea breathing gas (Heliox)", "Party balloons", "Inert shield gas in arc welding"],
    funFacts: [
      "Helium was discovered in the solar spectrum before it was found on Earth.",
      "At temperatures below 2.17 K, Helium-4 becomes a superfluid with zero viscosity."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Does not freeze at standard atmospheric pressure; requires 2.5 MPa of pressure."
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: "6.94 u",
    electronicConfiguration: "[He] 2s¹",
    electronShells: [2, 1],
    valenceElectrons: 1,
    group: 1,
    period: 2,
    block: "s",
    category: "alkali-metal",
    state: "Solid",
    protons: 3,
    neutrons: 4,
    electrons: 3,
    meltingPoint: "453.65 K (180.50 °C)",
    boilingPoint: "1603 K (1330 °C)",
    density: "0.534 g/cm³",
    electronegativity: 0.98,
    oxidationStates: "+1",
    discoveryYear: 1817,
    discoveredBy: "Johan August Arfwedson",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Rechargeable Lithium-ion batteries", "Mood-stabilizing psychiatric pharmaceuticals", "Specialty lubricating greases", "Heat-resistant glass and ceramics"],
    funFacts: [
      "Lithium is the least dense solid element on Earth; it floats on water and even hydrocarbon oils.",
      "It was one of the only three elements synthesized during the Big Bang along with H and He."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Highly reactive with water, releasing flammable hydrogen gas."
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: "9.0122 u",
    electronicConfiguration: "[He] 2s²",
    electronShells: [2, 2],
    valenceElectrons: 2,
    group: 2,
    period: 2,
    block: "s",
    category: "alkaline-earth",
    state: "Solid",
    protons: 4,
    neutrons: 5,
    electrons: 4,
    meltingPoint: "1560 K (1287 °C)",
    boilingPoint: "2742 K (2469 °C)",
    density: "1.85 g/cm³",
    electronegativity: 1.57,
    oxidationStates: "+2",
    discoveryYear: 1798,
    discoveredBy: "Louis-Nicolas Vauquelin",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["James Webb Space Telescope mirrors", "Aerospace structural components", "X-ray tube transmission windows", "Beryllium-copper non-sparking tools"],
    funFacts: [
      "Beryllium is transparent to X-rays, making it the premier material for radiation windows in particle physics.",
      "Its compounds taste sweet, giving it its early historic name 'Glucinium', but its dust is highly toxic."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Inhalation of dust causes the chronic lung condition berylliosis."
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: "10.81 u",
    electronicConfiguration: "[He] 2s² 2p¹",
    electronShells: [2, 3],
    valenceElectrons: 3,
    group: 13,
    period: 2,
    block: "p",
    category: "metalloid",
    state: "Solid",
    protons: 5,
    neutrons: 6,
    electrons: 5,
    meltingPoint: "2349 K (2076 °C)",
    boilingPoint: "4200 K (3927 °C)",
    density: "2.34 g/cm³",
    electronegativity: 2.04,
    oxidationStates: "+3, +2, +1",
    discoveryYear: 1808,
    discoveredBy: "Joseph Louis Gay-Lussac, Louis Jacques Thénard, Humphry Davy",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Borosilicate thermal shock-resistant glass (Pyrex)", "Fiberglass insulation", "Semiconductor dopant", "Nuclear reactor neutron absorbers"],
    funFacts: [
      "Amorphous boron burns with a distinctive vibrant green flame in pyrotechnic displays.",
      "Boron-10 has an exceptionally high neutron absorption cross-section."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Occurs naturally in mineral borax deposits."
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: "12.011 u",
    electronicConfiguration: "[He] 2s² 2p²",
    electronShells: [2, 4],
    valenceElectrons: 4,
    group: 14,
    period: 2,
    block: "p",
    category: "reactive-nonmetal",
    state: "Solid",
    protons: 6,
    neutrons: 6,
    electrons: 6,
    meltingPoint: "3823 K (3550 °C, diamond)",
    boilingPoint: "5100 K (4827 °C, sublimes)",
    density: "2.267 g/cm³ (graphite)",
    electronegativity: 2.55,
    oxidationStates: "+4, +3, +2, +1, 0, -1, -2, -3, -4",
    discoveryYear: "Ancient",
    discoveredBy: "Known to antiquity",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Basis of all organic chemistry and life", "Steel manufacturing", "Carbon fiber composites", "Radiocarbon dating (Carbon-14)"],
    funFacts: [
      "Carbon exhibits diverse allotropes: from the softest graphite to the hardest natural diamond, graphene, and fullerenes.",
      "Nearly 10 million distinct carbon compounds have been characterized by chemists."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Sublimes at atmospheric pressure around 3915 K."
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: "14.007 u",
    electronicConfiguration: "[He] 2s² 2p³",
    electronShells: [2, 5],
    valenceElectrons: 5,
    group: 15,
    period: 2,
    block: "p",
    category: "reactive-nonmetal",
    state: "Gas",
    protons: 7,
    neutrons: 7,
    electrons: 7,
    meltingPoint: "63.15 K (-210.00 °C)",
    boilingPoint: "77.36 K (-195.79 °C)",
    density: "1.2506 g/L",
    electronegativity: 3.04,
    oxidationStates: "+5, +4, +3, +2, +1, 0, -1, -2, -3",
    discoveryYear: 1772,
    discoveredBy: "Daniel Rutherford",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Fertilizers (Haber-Bosch process)", "Liquid nitrogen cryogenic preservation", "Food packaging atmosphere to prevent oxidation", "Explosives and propellants"],
    funFacts: [
      "Nitrogen gas (N₂) makes up approximately 78.08% of Earth's atmosphere.",
      "The triple bond in N₂ (945 kJ/mol) is one of the strongest chemical bonds known."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Essential building block of amino acids, proteins, and nucleic acids."
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: "15.999 u",
    electronicConfiguration: "[He] 2s² 2p⁴",
    electronShells: [2, 6],
    valenceElectrons: 6,
    group: 16,
    period: 2,
    block: "p",
    category: "reactive-nonmetal",
    state: "Gas",
    protons: 8,
    neutrons: 8,
    electrons: 8,
    meltingPoint: "54.36 K (-218.79 °C)",
    boilingPoint: "90.20 K (-182.95 °C)",
    density: "1.429 g/L",
    electronegativity: 3.44,
    oxidationStates: "-2, -1, +1, +2",
    discoveryYear: 1774,
    discoveredBy: "Carl Wilhelm Scheele, Joseph Priestley",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Cellular respiration and medical therapy", "Steel manufacturing and smelting", "Oxy-acetylene cutting torches", "Rocket propellant oxidizer (LOX)"],
    funFacts: [
      "Liquid oxygen has a striking pale sky-blue color and is strongly paramagnetic.",
      "Oxygen is the most abundant element in Earth's crust (approx. 46.6% by weight)."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Highly reactive second-most electronegative common element."
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: "18.998 u",
    electronicConfiguration: "[He] 2s² 2p⁵",
    electronShells: [2, 7],
    valenceElectrons: 7,
    group: 17,
    period: 2,
    block: "p",
    category: "reactive-nonmetal",
    state: "Gas",
    protons: 9,
    neutrons: 10,
    electrons: 9,
    meltingPoint: "53.53 K (-219.62 °C)",
    boilingPoint: "85.03 K (-188.12 °C)",
    density: "1.696 g/L",
    electronegativity: 3.98,
    oxidationStates: "-1",
    discoveryYear: 1886,
    discoveredBy: "Henri Moissan",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Toothpaste fluoride enamel protection", "Non-stick PTFE cookware (Teflon)", "Refrigerants and air conditioning fluids", "Uranium enrichment as UF₆"],
    funFacts: [
      "Fluorine is the most electronegative and chemically reactive of all chemical elements.",
      "It reacts vigorously with almost all organic and inorganic substances, even glass and water."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Extreme oxidizing power; Moissan won the 1906 Nobel Prize for isolating it."
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: "20.180 u",
    electronicConfiguration: "[He] 2s² 2p⁶",
    electronShells: [2, 8],
    valenceElectrons: 8,
    group: 18,
    period: 2,
    block: "p",
    category: "noble-gas",
    state: "Gas",
    protons: 10,
    neutrons: 10,
    electrons: 10,
    meltingPoint: "24.56 K (-248.59 °C)",
    boilingPoint: "27.07 K (-246.08 °C)",
    density: "0.9002 g/L",
    electronegativity: "Data not available",
    oxidationStates: "0",
    discoveryYear: 1898,
    discoveredBy: "William Ramsay, Morris Travers",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Neon glowing advertising signage", "High-voltage electrical indicators", "Helium-Neon optical lasers", "Cryogenic refrigerants"],
    funFacts: [
      "True neon signs glow with an unmistakable brilliant reddish-orange discharge light; other colors use different gases or phosphors.",
      "Neon is the fifth most abundant element in the cosmos by mass."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Chemically inert; forms no known stable neutral chemical compounds."
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: "22.990 u",
    electronicConfiguration: "[Ne] 3s¹",
    electronShells: [2, 8, 1],
    valenceElectrons: 1,
    group: 1,
    period: 3,
    block: "s",
    category: "alkali-metal",
    state: "Solid",
    protons: 11,
    neutrons: 12,
    electrons: 11,
    meltingPoint: "370.87 K (97.72 °C)",
    boilingPoint: "1156 K (883 °C)",
    density: "0.968 g/cm³",
    electronegativity: 0.93,
    oxidationStates: "+1",
    discoveryYear: 1807,
    discoveredBy: "Humphry Davy",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Table salt (NaCl) seasoning and food preservation", "Sodium-vapor street lighting", "Biological nerve transmission electrolyte", "Liquid coolant in fast breeder nuclear reactors"],
    funFacts: [
      "Sodium is so soft at room temperature that it can be sliced cleanly with a butter knife.",
      "Reacts violently with water in an exothermic reaction producing sodium hydroxide and hydrogen gas."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Stored under mineral oil or dry argon to prevent spontaneous air oxidation."
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: "24.305 u",
    electronicConfiguration: "[Ne] 3s²",
    electronShells: [2, 8, 2],
    valenceElectrons: 2,
    group: 2,
    period: 3,
    block: "s",
    category: "alkaline-earth",
    state: "Solid",
    protons: 12,
    neutrons: 12,
    electrons: 12,
    meltingPoint: "923 K (650 °C)",
    boilingPoint: "1363 K (1090 °C)",
    density: "1.738 g/cm³",
    electronegativity: 1.31,
    oxidationStates: "+2",
    discoveryYear: 1755,
    discoveredBy: "Joseph Black",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Lightweight aluminum-magnesium alloys for aerospace and vehicles", "Central coordination ion in plant chlorophyll", "Emergency fire-starters and flares", "Epsom salts and antacids (Milk of Magnesia)"],
    funFacts: [
      "Magnesium ribbon burns with an intense, blinding white light (over 3000 K) that cannot be extinguished by water.",
      "Essential for hundreds of human metabolic enzyme reactions and ATP stabilization."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Abundant in seawater and dolomite minerals."
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicMass: "26.982 u",
    electronicConfiguration: "[Ne] 3s² 3p¹",
    electronShells: [2, 8, 3],
    valenceElectrons: 3,
    group: 13,
    period: 3,
    block: "p",
    category: "post-transition",
    state: "Solid",
    protons: 13,
    neutrons: 14,
    electrons: 13,
    meltingPoint: "933.47 K (660.32 °C)",
    boilingPoint: "2792 K (2519 °C)",
    density: "2.70 g/cm³",
    electronegativity: 1.61,
    oxidationStates: "+3",
    discoveryYear: 1825,
    discoveredBy: "Hans Christian Ørsted",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Aircraft and automotive structural frames", "Beverage cans and food packaging foil", "High-voltage long-distance electrical power lines", "Modern architectural window frames"],
    funFacts: [
      "Aluminium is the most abundant metal in Earth's crust (approx. 8.1%).",
      "In the 19th century before the Hall-Héroult process, aluminium was more precious than silver and gold."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Passivates spontaneously with a microscopically thin, protective Al₂O₃ oxide layer."
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: "28.085 u",
    electronicConfiguration: "[Ne] 3s² 3p²",
    electronShells: [2, 8, 4],
    valenceElectrons: 4,
    group: 14,
    period: 3,
    block: "p",
    category: "metalloid",
    state: "Solid",
    protons: 14,
    neutrons: 14,
    electrons: 14,
    meltingPoint: "1687 K (1414 °C)",
    boilingPoint: "3538 K (3265 °C)",
    density: "2.329 g/cm³",
    electronegativity: 1.90,
    oxidationStates: "+4, +2, -4",
    discoveryYear: 1824,
    discoveredBy: "Jöns Jacob Berzelius",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Microchips, processors, and semiconductor transistors (Silicon Valley)", "Photovoltaic solar cells", "Silicone sealants and polymers", "Silica glass and ceramics"],
    funFacts: [
      "Silicon constitutes roughly 28% of Earth's crust, making it the second most abundant crustal element after oxygen.",
      "Ultra-pure silicon crystals (99.9999999% purity) are produced via the Czochralski process for microprocessors."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Crucial backbone of modern semiconductor technology."
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: "30.974 u",
    electronicConfiguration: "[Ne] 3s² 3p³",
    electronShells: [2, 8, 5],
    valenceElectrons: 5,
    group: 15,
    period: 3,
    block: "p",
    category: "reactive-nonmetal",
    state: "Solid",
    protons: 15,
    neutrons: 16,
    electrons: 15,
    meltingPoint: "317.30 K (44.15 °C, white)",
    boilingPoint: "553.65 K (280.5 °C)",
    density: "1.823 g/cm³ (white)",
    electronegativity: 2.19,
    oxidationStates: "+5, +4, +3, +1, 0, -3",
    discoveryYear: 1669,
    discoveredBy: "Hennig Brand",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Agricultural phosphate fertilizers", "Safety matches and flares (red phosphorus)", "Structural component of DNA, RNA, and cellular ATP", "Detergents and rust removers (phosphoric acid)"],
    funFacts: [
      "Discovered by alchemist Hennig Brand while attempting to distill gold from human urine.",
      "White phosphorus glows green in the dark (chemiluminescence) when exposed to oxygen."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Exhibits distinct allotropes: highly toxic pyrophoric white, stable red, and conductive black phosphorus."
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: "32.06 u",
    electronicConfiguration: "[Ne] 3s² 3p⁴",
    electronShells: [2, 8, 6],
    valenceElectrons: 6,
    group: 16,
    period: 3,
    block: "p",
    category: "reactive-nonmetal",
    state: "Solid",
    protons: 16,
    neutrons: 16,
    electrons: 16,
    meltingPoint: "388.36 K (115.21 °C)",
    boilingPoint: "717.8 K (444.6 °C)",
    density: "2.07 g/cm³",
    electronegativity: 2.58,
    oxidationStates: "+6, +4, +2, +1, 0, -2",
    discoveryYear: "Ancient",
    discoveredBy: "Known to antiquity",
    phaseAtRoomTemperature: "Solid",
    commonUses: ["Sulfuric acid (H₂SO₄) industrial production", "Rubber vulcanization", "Gunpowder and pyrotechnics", "Pharmaceuticals and antifungal treatments"],
    funFacts: [
      "Pure elemental sulfur is an odorless bright yellow crystalline solid; the foul rotten-egg smell comes from hydrogen sulfide (H₂S).",
      "Disulfide bonds in keratin proteins give human hair its curl and structure."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Found in volcanic deposits and elemental salt domes."
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: "35.45 u",
    electronicConfiguration: "[Ne] 3s² 3p⁵",
    electronShells: [2, 8, 7],
    valenceElectrons: 7,
    group: 17,
    period: 3,
    block: "p",
    category: "reactive-nonmetal",
    state: "Gas",
    protons: 17,
    neutrons: 18,
    electrons: 17,
    meltingPoint: "171.6 K (-101.5 °C)",
    boilingPoint: "239.11 K (-34.04 °C)",
    density: "3.2 g/L",
    electronegativity: 3.16,
    oxidationStates: "+7, +5, +3, +1, -1",
    discoveryYear: 1774,
    discoveredBy: "Carl Wilhelm Scheele",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Drinking water disinfection and swimming pool sanitization", "PVC (polyvinyl chloride) piping manufacturing", "Bleach and cleaning agents", "Synthesis of pharmaceuticals and agrochemicals"],
    funFacts: [
      "Chlorine gas is a pungent yellow-green gas approximately 2.5 times denser than ambient air.",
      "Chlorine disinfection of public municipal water supply is hailed as one of the greatest public health triumphs in human history."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Strong oxidizer; corrosive and toxic in pure gaseous form."
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: "39.948 u",
    electronicConfiguration: "[Ne] 3s² 3p⁶",
    electronShells: [2, 8, 8],
    valenceElectrons: 8,
    group: 18,
    period: 3,
    block: "p",
    category: "noble-gas",
    state: "Gas",
    protons: 18,
    neutrons: 22,
    electrons: 18,
    meltingPoint: "83.81 K (-189.34 °C)",
    boilingPoint: "87.30 K (-185.85 °C)",
    density: "1.784 g/L",
    electronegativity: "Data not available",
    oxidationStates: "0",
    discoveryYear: 1894,
    discoveredBy: "Lord Rayleigh, William Ramsay",
    phaseAtRoomTemperature: "Gas",
    commonUses: ["Shielding gas for TIG and MIG metal welding", "Filling double-pane thermal insulating windows", "Incandescent and fluorescent light bulbs", "Preserving historical documents and fine vintage wines"],
    funFacts: [
      "Argon is the third most abundant gas in Earth's atmosphere (0.934% by volume), more abundant than CO₂.",
      "Its name originates from the Greek word 'argos', meaning 'lazy' or 'idle', reflecting its extreme chemical inertness."
    ],
    dataSource: "IUPAC / NIST Reference",
    dataNotes: "Produced commercially through the fractional distillation of liquid air."
  }
];

// Helper to generate authoritative scientifically verified data for elements 19 through 118
(function generateAll118Elements() {
  const elementsSpecs = [
    { z: 19, s: "K", n: "Potassium", m: "39.098 u", g: 1, p: 4, b: "s", c: "alkali-metal", st: "Solid", cfg: "[Ar] 4s¹", mp: "336.7 K (63.5 °C)", bp: "1032 K (759 °C)", d: "0.862 g/cm³", en: 0.82, ox: "+1", yr: 1807, by: "Humphry Davy", uses: ["NPK agricultural fertilizers", "Potassium-argon geological dating", "Electrolyte for neuromuscular transmission", "Potassium hydroxide industrial soapmaking"] },
    { z: 20, s: "Ca", n: "Calcium", m: "40.078 u", g: 2, p: 4, b: "s", c: "alkaline-earth", st: "Solid", cfg: "[Ar] 4s²", mp: "1115 K (842 °C)", bp: "1757 K (1484 °C)", d: "1.55 g/cm³", en: 1.00, ox: "+2", yr: 1808, by: "Humphry Davy", uses: ["Structural bones and teeth mineralization", "Portland cement and concrete construction", "Steel deoxidizer", "Plaster of Paris and drywall"] },
    { z: 21, s: "Sc", n: "Scandium", m: "44.956 u", g: 3, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d¹ 4s²", mp: "1814 K (1541 °C)", bp: "3109 K (2836 °C)", d: "2.985 g/cm³", en: 1.36, ox: "+3", yr: 1879, by: "Lars Fredrik Nilson", uses: ["Aerospace aluminium-scandium alloys", "High-intensity metal-halide stadium lighting", "High-end bicycle frames", "Solid oxide fuel cells"] },
    { z: 22, s: "Ti", n: "Titanium", m: "47.867 u", g: 4, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d² 4s²", mp: "1941 K (1668 °C)", bp: "3560 K (3287 °C)", d: "4.506 g/cm³", en: 1.54, ox: "+4, +3, +2", yr: 1791, by: "William Gregor", uses: ["Aerospace supersonic airframes and jet engines", "Biocompatible surgical implants and joint replacements", "Titanium dioxide (TiO₂) brilliant white pigment", "Marine saltwater desalinization components"] },
    { z: 23, s: "V", n: "Vanadium", m: "50.942 u", g: 5, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d³ 4s²", mp: "2183 K (1910 °C)", bp: "3680 K (3407 °C)", d: "6.11 g/cm³", en: 1.63, ox: "+5, +4, +3, +2", yr: 1801, by: "Andrés Manuel del Río", uses: ["Vanadium steel high-strength structural rebar and hand tools", "Vanadium redox flow grid-scale energy storage batteries", "Sulfuric acid production catalyst (V₂O₅)", "Superconducting magnets"] },
    { z: 24, s: "Cr", n: "Chromium", m: "51.996 u", g: 6, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d⁵ 4s¹", mp: "2180 K (1907 °C)", bp: "2944 K (2671 °C)", d: "7.19 g/cm³", en: 1.66, ox: "+6, +3, +2", yr: 1797, by: "Louis-Nicolas Vauquelin", uses: ["Stainless steel corrosion resistance (minimum 10.5% Cr)", "Hard chrome electroplating for automotive parts", "Leather tanning tanning chemicals", "Chrome green and yellow industrial pigments"] },
    { z: 25, s: "Mn", n: "Manganese", m: "54.938 u", g: 7, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d⁵ 4s²", mp: "1519 K (1246 °C)", bp: "2334 K (2061 °C)", d: "7.21 g/cm³", en: 1.55, ox: "+7, +4, +3, +2", yr: 1774, by: "Johan Gottlieb Gahn", uses: ["Essential deoxidizing alloying agent in all steelmaking", "Alkaline and lithium-manganese batteries", "Photosynthetic water-splitting enzyme complex (Photosystem II)", "Potassium permanganate disinfectant (KMnO₄)"] },
    { z: 26, s: "Fe", n: "Iron", m: "55.845 u", g: 8, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d⁶ 4s²", mp: "1811 K (1538 °C)", bp: "3134 K (2862 °C)", d: "7.874 g/cm³", en: 1.83, ox: "+3, +2", yr: "Ancient", by: "Known to antiquity", uses: ["Primary component of structural steel and cast iron", "Hemoglobin oxygen transport in mammalian bloodstream", "Industrial Haber-Bosch ammonia synthesis catalysts", "Electromagnets and transformer magnetic cores"] },
    { z: 27, s: "Co", n: "Cobalt", m: "58.933 u", g: 9, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d⁷ 4s²", mp: "1768 K (1495 °C)", bp: "3200 K (2927 °C)", d: "8.90 g/cm³", en: 1.88, ox: "+3, +2", yr: 1735, by: "Georg Brandt", uses: ["High-energy lithium-ion battery cathodes (NMC / LCO)", "High-temperature jet engine superalloys", "Cobalt-60 radiation therapy and food sterilization", "Cobalt blue vibrant ceramic glass pigments"] },
    { z: 28, s: "Ni", n: "Nickel", m: "58.693 u", g: 10, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d⁸ 4s²", mp: "1728 K (1455 °C)", bp: "3003 K (2730 °C)", d: "8.908 g/cm³", en: 1.91, ox: "+3, +2", yr: 1751, by: "Axel Fredrik Cronstedt", uses: ["Austenitic stainless steels (adds ductility and corrosion resistance)", "Electric vehicle battery chemistries", "Electroplating and coinage alloys", "Hydrogenation catalysts in vegetable oil margarine production"] },
    { z: 29, s: "Cu", n: "Copper", m: "63.546 u", g: 11, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s¹", mp: "1357.77 K (1084.62 °C)", bp: "2835 K (2562 °C)", d: "8.96 g/cm³", en: 1.90, ox: "+2, +1", yr: "Ancient", by: "Known to antiquity", uses: ["Electrical wiring, motors, and electronic interconnects", "Plumbing water pipes and fittings", "Brass and bronze structural engineering alloys", "Antimicrobial touch surfaces in healthcare facilities"] },
    { z: 30, s: "Zn", n: "Zinc", m: "65.38 u", g: 12, p: 4, b: "d", c: "transition-metal", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s²", mp: "692.68 K (419.53 °C)", bp: "1180 K (907 °C)", d: "7.14 g/cm³", en: 1.65, ox: "+2", yr: "Ancient", by: "Indian and Chinese metallurgists", uses: ["Hot-dip galvanization to prevent steel rusting", "Brass alloy (copper-zinc) musical instruments", "Zinc-carbon and alkaline batteries", "Zinc oxide sunscreen and skin ointments"] },
    { z: 31, s: "Ga", n: "Gallium", m: "69.723 u", g: 13, p: 4, b: "p", c: "post-transition", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s² 4p¹", mp: "302.91 K (29.76 °C)", bp: "2673 K (2400 °C)", d: "5.91 g/cm³", en: 1.81, ox: "+3", yr: 1875, by: "Paul-Émile Lecoq de Boisbaudran", uses: ["Gallium Arsenide (GaAs) high-frequency RF integrated circuits", "Gallium Nitride (GaN) high-efficiency power semiconductors & blue LEDs", "Galinstan non-toxic liquid thermometers", "Laser diodes"] },
    { z: 32, s: "Ge", n: "Germanium", m: "72.630 u", g: 14, p: 4, b: "p", c: "metalloid", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s² 4p²", mp: "1211.40 K (938.25 °C)", bp: "3106 K (2833 °C)", d: "5.323 g/cm³", en: 2.01, ox: "+4, +2", yr: 1886, by: "Clemens Winkler", uses: ["Fiber-optic core glass refractive index modifier", "Infrared night-vision optical lenses", "Polymerization catalysts for PET plastics", "High-efficiency multi-junction space solar cells"] },
    { z: 33, s: "As", n: "Arsenic", m: "74.922 u", g: 15, p: 4, b: "p", c: "metalloid", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s² 4p³", mp: "1090 K (817 °C, at 2.8 MPa)", bp: "887 K (614 °C, sublimes)", d: "5.727 g/cm³", en: 2.18, ox: "+5, +3, -3", yr: "Ancient", by: "Albertus Magnus (1250)", uses: ["GaAs semiconductor dopant in high-speed microchips", "Lead-acid battery grid strengthening alloy", "Arsenic trioxide chemotherapy for acute promyelocytic leukemia", "Wood preservative compounds (historic)"] },
    { z: 34, s: "Se", n: "Selenium", m: "78.971 u", g: 16, p: 4, b: "p", c: "reactive-nonmetal", st: "Solid", cfg: "[Ar] 3d¹⁰ 4s² 4p⁴", mp: "494 K (221 °C)", bp: "958 K (685 °C)", d: "4.81 g/cm³", en: 2.55, ox: "+6, +4, -2", yr: 1817, by: "Jöns Jacob Berzelius", uses: ["Decolorizing glass and red ruby glass manufacturing", "Photoreceptor drums in photocopiers and laser printers", "Essential biological dietary trace micronutrient (Selenoproteins)", "CIGS thin-film photovoltaic solar cells"] },
    { z: 35, s: "Br", n: "Bromine", m: "79.904 u", g: 17, p: 4, b: "p", c: "reactive-nonmetal", st: "Liquid", cfg: "[Ar] 3d¹⁰ 4s² 4p⁵", mp: "265.8 K (-7.3 °C)", bp: "332.0 K (58.8 °C)", d: "3.1028 g/cm³", en: 2.96, ox: "+5, +3, +1, -1", yr: 1826, by: "Antoine Jérôme Balard, Carl Löwig", uses: ["Brominated flame retardants in plastics and electronics", "Agricultural pest fumigants", "Water purification in spas and cooling towers", "Pharmaceutical intermediates"] },
    { z: 36, s: "Kr", n: "Krypton", m: "83.798 u", g: 18, p: 4, b: "p", c: "noble-gas", st: "Gas", cfg: "[Ar] 3d¹⁰ 4s² 4p⁶", mp: "115.79 K (-157.36 °C)", bp: "119.93 K (-153.22 °C)", d: "3.749 g/L", en: 3.00, ox: "+2, 0", yr: 1898, by: "William Ramsay, Morris Travers", uses: ["High-efficiency energy-saving insulated window glass filling", "Krypton-fluoride excimer lasers for photolithography", "Airport runway approach flash lighting", "Historic standard definition of the meter (1960-1983)"] },
    { z: 37, s: "Rb", n: "Rubidium", m: "85.468 u", g: 1, p: 5, b: "s", c: "alkali-metal", st: "Solid", cfg: "[Kr] 5s¹", mp: "312.46 K (39.31 °C)", bp: "961 K (688 °C)", d: "1.532 g/cm³", en: 0.82, ox: "+1", yr: 1861, by: "Robert Bunsen, Gustav Kirchhoff", uses: ["Ultra-precise atomic frequency standards and clocks", "Bose-Einstein condensate quantum physics experiments", "Specialty night vision vacuum photocathodes", "Purple-red pyrotechnic displays"] },
    { z: 38, s: "Sr", n: "Strontium", m: "87.62 u", g: 2, p: 5, b: "s", c: "alkaline-earth", st: "Solid", cfg: "[Kr] 5s²", mp: "1050 K (777 °C)", bp: "1655 K (1382 °C)", d: "2.64 g/cm³", en: 0.95, ox: "+2", yr: 1790, by: "Adair Crawford", uses: ["Vibrant crimson red fireworks and military signal flares", "Strontium-90 radioisotope thermoelectric generators (RTGs)", "Strontium aluminate phosphorescent glow-in-the-dark paints", "Optical lattice atomic clocks"] },
    { z: 39, s: "Y", n: "Yttrium", m: "88.906 u", g: 3, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d¹ 5s²", mp: "1799 K (1526 °C)", bp: "3609 K (3336 °C)", d: "4.472 g/cm³", en: 1.22, ox: "+3", yr: 1794, by: "Johan Gadolin", uses: ["YBCO high-temperature superconductors (liquid nitrogen cooled)", "YAG (yttrium aluminum garnet) surgical and industrial cutting lasers", "Red phosphors in cathode ray tubes and LEDs", "Zirconia ceramic stabilization"] },
    { z: 40, s: "Zr", n: "Zirconium", m: "91.224 u", g: 4, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d² 5s²", mp: "2128 K (1855 °C)", bp: "4682 K (4409 °C)", d: "6.52 g/cm³", en: 1.33, ox: "+4", yr: 1789, by: "Martin Heinrich Klaproth", uses: ["Nuclear reactor uranium fuel rod cladding (low neutron cross-section)", "Cubic zirconia synthetic gemstone diamonds", "Corrosion-proof chemical processing valves and pumps", "High-performance ceramic dental crowns"] },
    { z: 41, s: "Nb", n: "Niobium", m: "92.906 u", g: 5, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d⁴ 5s¹", mp: "2750 K (2477 °C)", bp: "5017 K (4744 °C)", d: "8.57 g/cm³", en: 1.6, ox: "+5, +3", yr: 1801, by: "Charles Hatchett", uses: ["Superconducting magnets in MRI machines and particle accelerators", "High-strength low-alloy structural steel pipelines and bridges", "Rocket nozzle superalloys (SpaceX Merlin engines)", "Hypoallergenic anodized medical jewelry"] },
    { z: 42, s: "Mo", n: "Molybdenum", m: "95.95 u", g: 6, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d⁵ 5s¹", mp: "2896 K (2623 °C)", bp: "4912 K (4639 °C)", d: "10.28 g/cm³", en: 2.16, ox: "+6, +4, +3", yr: 1778, by: "Carl Wilhelm Scheele", uses: ["Moly steel alloys for high-temperature turbine blades", "Molybdenum disulfide (MoS₂) high-pressure solid lubricant", "Molybdenum-99 precursor for medical imaging isotope Technetium-99m", "Petroleum hydrodesulfurization catalysts"] },
    { z: 43, s: "Tc", n: "Technetium", m: "[98] u", g: 7, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d⁵ 5s²", mp: "2430 K (2157 °C)", bp: "4538 K (4265 °C)", d: "11 g/cm³", en: 1.9, ox: "+7, +4", yr: 1937, by: "Emilio Segrè, Carlo Perrier", uses: ["Technetium-99m nuclear medicine diagnostic imaging scans (bone, heart, brain)", "Corrosion inhibition research", "Beta particle calibration source", "First artificially synthesized element in history"] },
    { z: 44, s: "Ru", n: "Ruthenium", m: "101.07 u", g: 8, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d⁷ 5s¹", mp: "2607 K (2334 °C)", bp: "4423 K (4150 °C)", d: "12.45 g/cm³", en: 2.2, ox: "+8, +4, +3", yr: 1844, by: "Karl Ernst Claus", uses: ["Hard disk drive magnetic recording read-heads (GMR layers)", "Wear-resistant electrical contacts and chip resistors", "Grubbs' catalysts in organic olefin metathesis", "Dye-sensitized solar cells"] },
    { z: 45, s: "Rh", n: "Rhodium", m: "102.91 u", g: 9, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d⁸ 5s¹", mp: "2237 K (1964 °C)", bp: "3968 K (3695 °C)", d: "12.41 g/cm³", en: 2.28, ox: "+3", yr: 1803, by: "William Hyde Wollaston", uses: ["Automotive catalytic converters (reduces nitrogen oxides NOx)", "Rhodium plating for ultra-reflective white gold jewelry", "High-temperature thermocouple wires", "Industrial acetic acid synthesis catalysts"] },
    { z: 46, s: "Pd", n: "Palladium", m: "106.42 u", g: 10, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d¹⁰", mp: "1828.05 K (1554.9 °C)", bp: "3236 K (2963 °C)", d: "12.023 g/cm³", en: 2.20, ox: "+4, +2, 0", yr: 1802, by: "William Hyde Wollaston", uses: ["Automotive catalytic converters (oxidizes CO and unburnt hydrocarbons)", "Multilayer ceramic chip capacitors (MLCCs)", "Hydrogen purification membrane filters", "Cross-coupling organic reaction catalysts (Suzuki-Miyaura)"] },
    { z: 47, s: "Ag", n: "Silver", m: "107.87 u", g: 11, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s¹", mp: "1234.93 K (961.78 °C)", bp: "2435 K (2162 °C)", d: "10.49 g/cm³", en: 1.93, ox: "+1", yr: "Ancient", by: "Known to antiquity", uses: ["Photovoltaic solar panel conductive contact paste", "Highest electrical and thermal conductivity of all metals", "Sterling silverware and jewelry", "Antibacterial wound dressings and water filters"] },
    { z: 48, s: "Cd", n: "Cadmium", m: "112.41 u", g: 12, p: 5, b: "d", c: "transition-metal", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s²", mp: "594.22 K (321.07 °C)", bp: "1040 K (767 °C)", d: "8.65 g/cm³", en: 1.69, ox: "+2", yr: 1817, by: "Karl Samuel Leberecht Hermann, Friedrich Stromeyer", uses: ["Nickel-Cadmium (NiCad) rechargeable batteries", "Cadmium Telluride (CdTe) thin-film solar panels", "Nuclear control rods (high thermal neutron absorption)", "Cadmium yellow, orange, and red artist pigments"] },
    { z: 49, s: "In", n: "Indium", m: "114.82 u", g: 13, p: 5, b: "p", c: "post-transition", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s² 5p¹", mp: "429.75 K (156.60 °C)", bp: "2345 K (2072 °C)", d: "7.31 g/cm³", en: 1.78, ox: "+3", yr: 1863, by: "Ferdinand Reich, Hieronymous Theodor Richter", uses: ["Indium Tin Oxide (ITO) transparent conductive coatings on touchscreens & OLEDs", "Low-melting thermal interface alloys and solders", "Cryogenic ultra-high vacuum indium gasket seals", "InGaAs infrared photodetectors"] },
    { z: 50, s: "Sn", n: "Tin", m: "118.71 u", g: 14, p: 5, b: "p", c: "post-transition", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s² 5p²", mp: "505.08 K (231.93 °C)", bp: "2875 K (2602 °C)", d: "7.365 g/cm³", en: 1.96, ox: "+4, +2", yr: "Ancient", by: "Known to antiquity", uses: ["Lead-free electronic soldering alloys (SAC305)", "Tinplate corrosion-resistant food preservation cans", "Float glass manufacturing molten bath", "Bronze alloy component (copper + tin)"] },
    { z: 51, s: "Sb", n: "Antimony", m: "121.76 u", g: 15, p: 5, b: "p", c: "metalloid", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s² 5p³", mp: "903.78 K (630.63 °C)", bp: "1908 K (1635 °C)", d: "6.697 g/cm³", en: 2.05, ox: "+5, +3, -3", yr: "Ancient", by: "Known to antiquity", uses: ["Antimony trioxide synergist in halogenated flame retardants", "Hardening lead in automotive lead-acid batteries", "Infrared optical detectors and thermoelectrics (Bi₂Te₃/Sb₂Te₃)", "Historic kohl eye cosmetics"] },
    { z: 52, s: "Te", n: "Tellurium", m: "127.60 u", g: 16, p: 5, b: "p", c: "metalloid", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s² 5p⁴", mp: "722.66 K (449.51 °C)", bp: "1261 K (988 °C)", d: "6.24 g/cm³", en: 2.1, ox: "+6, +4, -2", yr: 1782, by: "Franz-Joseph Müller von Reichenstein", uses: ["Cadmium Telluride (CdTe) utility-scale solar panels", "Phase-change memory (PCM) and rewritable optical discs", "Thermoelectric Peltier cooling modules (Bi₂Te₃)", "Steel and copper machinability additive"] },
    { z: 53, s: "I", n: "Iodine", m: "126.90 u", g: 17, p: 5, b: "p", c: "reactive-nonmetal", st: "Solid", cfg: "[Kr] 4d¹⁰ 5s² 5p⁵", mp: "386.85 K (113.7 °C)", bp: "457.4 K (184.3 °C)", d: "4.933 g/cm³", en: 2.66, ox: "+7, +5, +1, -1", yr: 1811, by: "Bernard Courtois", uses: ["Iodized table salt to prevent goiter and thyroid deficiency", "Povidone-iodine medical antiseptic disinfectant", "X-ray radiocontrast agents (CT scans)", "Polarizing optical film filters for LCD displays"] },
    { z: 54, s: "Xe", n: "Xenon", m: "131.29 u", g: 18, p: 5, b: "p", c: "noble-gas", st: "Gas", cfg: "[Kr] 4d¹⁰ 5s² 5p⁶", mp: "161.40 K (-111.75 °C)", bp: "165.05 K (-108.1 °C)", d: "5.894 g/L", en: 2.60, ox: "+8, +6, +4, +2, 0", yr: 1898, by: "William Ramsay, Morris Travers", uses: ["Ion thruster propellant for deep space satellites and probes", "High-intensity Xenon arc cinema projector bulbs", "Neuroprotective general anesthetic", "Liquid xenon dark matter particle detectors (XENONnT, LUX-ZEPLIN)"] },
    { z: 55, s: "Cs", n: "Caesium", m: "132.91 u", g: 1, p: 6, b: "s", c: "alkali-metal", st: "Solid", cfg: "[Xe] 6s¹", mp: "301.59 K (28.44 °C)", bp: "944 K (671 °C)", d: "1.93 g/cm³", en: 0.79, ox: "+1", yr: 1860, by: "Robert Bunsen, Gustav Kirchhoff", uses: ["Primary atomic clock standard defining the SI Second (9,192,631,770 Hz)", "Caesium formate high-density drilling fluids in oil extraction", "Photoelectric cells and night vision infrared devices", "Cancer brachytherapy (Cs-131)"] },
    { z: 56, s: "Ba", n: "Barium", m: "137.33 u", g: 2, p: 6, b: "s", c: "alkaline-earth", st: "Solid", cfg: "[Xe] 6s²", mp: "1000 K (727 °C)", bp: "2170 K (1897 °C)", d: "3.51 g/cm³", en: 0.89, ox: "+2", yr: 1774, by: "Carl Wilhelm Scheele", uses: ["Barium swallow (BaSO₄) medical gastrointestinal X-ray imaging", "Heavy drilling mud weighting agent in petroleum wells", "Vivid green fireworks pyrotechnics", "Vacuum tube residual gas getter"] },
    { z: 57, s: "La", n: "Lanthanum", m: "138.91 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 5d¹ 6s²", mp: "1193 K (920 °C)", bp: "3737 K (3464 °C)", d: "6.162 g/cm³", en: 1.10, ox: "+3", yr: 1839, by: "Carl Gustaf Mosander", uses: ["High-refractive index optical glass for camera and telescope lenses", "NiMH rechargeable battery metal-hydride electrodes", "Petroleum fluid catalytic cracking catalysts", "Carbon arc studio lighting"] },
    { z: 58, s: "Ce", n: "Cerium", m: "140.12 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹ 5d¹ 6s²", mp: "1068 K (795 °C)", bp: "3716 K (3443 °C)", d: "6.770 g/cm³", en: 1.12, ox: "+4, +3", yr: 1803, by: "Martin Heinrich Klaproth, Jöns Jacob Berzelius, Wilhelm Hisinger", uses: ["Cerium oxide (CeO₂) precision optical glass polishing compound", "Automotive catalytic converter oxygen storage promoter", "Mischmetal alloy in cigarette lighter flints", "Self-cleaning oven catalysts"] },
    { z: 59, s: "Pr", n: "Praseodymium", m: "140.91 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f³ 6s²", mp: "1208 K (935 °C)", bp: "3793 K (3520 °C)", d: "6.77 g/cm³", en: 1.13, ox: "+4, +3", yr: 1885, by: "Carl Auer von Welsbach", uses: ["Didymium glass for glassblower and welder protective goggles", "High-strength neodymium-praseodymium permanent magnets (NdFeB)", "Vibrant yellow ceramic tile glaze pigment", "Aircraft engine magnesium alloy strengthening"] },
    { z: 60, s: "Nd", n: "Neodymium", m: "144.24 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁴ 6s²", mp: "1297 K (1024 °C)", bp: "3347 K (3074 °C)", d: "7.01 g/cm³", en: 1.14, ox: "+3", yr: 1885, by: "Carl Auer von Welsbach", uses: ["NdFeB ultra-powerful permanent magnets (EV traction motors & wind turbine generators)", "Nd:YAG high-energy surgical and cutting lasers", "Purple-colored art glass and didymium lenses", "Hard disk drive voice coil actuators"] },
    { z: 61, s: "Pm", n: "Promethium", m: "[145] u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁵ 6s²", mp: "1315 K (1042 °C)", bp: "3273 K (3000 °C)", d: "7.26 g/cm³", en: 1.13, ox: "+3", yr: 1945, by: "Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell", uses: ["Luminous phosphorescent paint for military instruments & watch dials", "Long-life atomic radioisotope batteries for spacecraft and pacemakers", "Industrial beta-backscatter thickness gauges", "Only naturally radioactive lanthanide"] },
    { z: 62, s: "Sm", n: "Samarium", m: "150.36 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁶ 6s²", mp: "1345 K (1072 °C)", bp: "2067 K (1794 °C)", d: "7.52 g/cm³", en: 1.17, ox: "+3, +2", yr: 1879, by: "Paul-Émile Lecoq de Boisbaudran", uses: ["Samarium-Cobalt (SmCo) high-temperature permanent magnets (defense/aerospace)", "Samarium-153 (Quadramet) targeted bone cancer pain radiotherapy", "Nuclear reactor control rod neutron absorbers", "Kagan's reagent (SmI₂) in organic synthesis"] },
    { z: 63, s: "Eu", n: "Europium", m: "151.96 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁷ 6s²", mp: "1099 K (826 °C)", bp: "1802 K (1529 °C)", d: "5.244 g/cm³", en: 1.2, ox: "+3, +2", yr: 1901, by: "Eugène-Anatole Demarçay", uses: ["Red and blue phosphors in Euro banknotes anti-counterfeiting security features", "Phosphors in color television screens and trichromatic fluorescent lamps", "Quantum memory crystals", "Nuclear control rods"] },
    { z: 64, s: "Gd", n: "Gadolinium", m: "157.25 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁷ 5d¹ 6s²", mp: "1585 K (1312 °C)", bp: "3546 K (3273 °C)", d: "7.90 g/cm³", en: 1.20, ox: "+3", yr: 1880, by: "Jean Charles Galissard de Marignac", uses: ["Intravenous MRI contrast agents (paramagnetic Gd complexes)", "Magnetic refrigeration (giant magnetocaloric effect)", "Neutron radiography and shielding (highest thermal neutron capture of all elements)", "X-ray phosphor screens"] },
    { z: 65, s: "Tb", n: "Terbium", m: "158.93 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f⁹ 6s²", mp: "1629 K (1356 °C)", bp: "3503 K (3230 °C)", d: "8.23 g/cm³", en: 1.2, ox: "+4, +3", yr: 1843, by: "Carl Gustaf Mosander", uses: ["Green phosphors for color displays and high-efficiency lighting", "Terfenol-D giant magnetostrictive sonar transducers and actuators", "Magneto-optical storage discs", "Solid-state lasers"] },
    { z: 66, s: "Dy", n: "Dysprosium", m: "162.50 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹⁰ 6s²", mp: "1680 K (1407 °C)", bp: "2840 K (2567 °C)", d: "8.540 g/cm³", en: 1.22, ox: "+3", yr: 1886, by: "Paul-Émile Lecoq de Boisbaudran", uses: ["Thermal demagnetization inhibitor in high-performance EV electric motor NdFeB magnets", "Nuclear reactor control rods", "Terfenol-D magnetostrictive actuators", "High-intensity metal-halide lighting lamps"] },
    { z: 67, s: "Ho", n: "Holmium", m: "164.93 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹¹ 6s²", mp: "1734 K (1461 °C)", bp: "2993 K (2720 °C)", d: "8.79 g/cm³", en: 1.23, ox: "+3", yr: 1878, by: "Marc Delafontaine, Jacques-Louis Soret, Per Teodor Cleve", uses: ["Ho:YAG medical cutting lasers for urological and orthopedic surgery", "Highest magnetic moment of any element (flux concentrators for pole pieces)", "Yellow and pink art glass tinting", "Nuclear reactor burnable neutron poisons"] },
    { z: 68, s: "Er", n: "Erbium", m: "167.26 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹² 6s²", mp: "1802 K (1529 °C)", bp: "3141 K (2868 °C)", d: "9.066 g/cm³", en: 1.24, ox: "+3", yr: 1843, by: "Carl Gustaf Mosander", uses: ["Erbium-Doped Fiber Amplifiers (EDFA) powering global transoceanic internet fiber optics", "Er:YAG cosmetic skin resurfacing and dental lasers", "Pink art glass and porcelain glazes", "Neutron-absorbing reactor control rods"] },
    { z: 69, s: "Tm", n: "Thulium", m: "168.93 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹³ 6s²", mp: "1818 K (1545 °C)", bp: "2223 K (1950 °C)", d: "9.32 g/cm³", en: 1.25, ox: "+3, +2", yr: 1879, by: "Per Teodor Cleve", uses: ["Portable medical X-ray imaging devices (Thulium-170 isotope)", "Thulium fiber lasers for high-precision surgical resection", "Euro banknote security blue fluorescent phosphors", "High-temperature superconductor research"] },
    { z: 70, s: "Yb", n: "Ytterbium", m: "173.05 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹⁴ 6s²", mp: "1097 K (824 °C)", bp: "1469 K (1196 °C)", d: "6.90 g/cm³", en: 1.1, ox: "+3, +2", yr: 1878, by: "Jean Charles Galissard de Marignac", uses: ["Optical atomic lattice clocks (accurate to 1 second in 10 billion years)", "Ytterbium fiber lasers for industrial metal welding and cutting", "Stainless steel stress and earthquake seismograph pressure sensors", "Cancer radiation source"] },
    { z: 71, s: "Lu", n: "Lutetium", m: "174.97 u", g: "f-block", p: 6, b: "f", c: "lanthanide", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹ 6s²", mp: "1925 K (1652 °C)", bp: "3675 K (3402 °C)", d: "9.841 g/cm³", en: 1.27, ox: "+3", yr: 1907, by: "Georges Urbain, Carl Auer von Welsbach", uses: ["Lutetium-177 (Pluvicto/Lutathera) targeted prostate and neuroendocrine cancer radioligand therapy", "LSO scintillation crystals in PET medical imaging scanners", "Petroleum catalytic cracking catalysts", "LED phosphor host crystals"] },
    { z: 72, s: "Hf", n: "Hafnium", m: "178.49 u", g: 4, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d² 6s²", mp: "2506 K (2233 °C)", bp: "4876 K (4603 °C)", d: "13.31 g/cm³", en: 1.3, ox: "+4", yr: 1923, by: "Dirk Coster, George de Hevesy", uses: ["High-k dielectric gate insulator oxide in modern Intel/AMD microprocessor transistors", "Nuclear submarine control rods (excellent thermal neutron capture)", "Plasma cutting torch electrode tips", "Superalloys for aerospace turbine blades"] },
    { z: 73, s: "Ta", n: "Tantalum", m: "180.95 u", g: 5, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d³ 6s²", mp: "3290 K (3017 °C)", bp: "5731 K (5458 °C)", d: "16.69 g/cm³", en: 1.5, ox: "+5", yr: 1802, by: "Anders Gustaf Ekeberg", uses: ["Ultra-compact high-capacitance electrolytic capacitors for smartphones and computers", "Biocompatible surgical implants, cranial plates, and vascular clips", "Chemical plant acid-proof heat exchangers", "High-melting carbide cutting tools (TaC)"] },
    { z: 74, s: "W", n: "Tungsten", m: "183.84 u", g: 6, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d⁴ 6s²", mp: "3695 K (3422 °C)", bp: "6203 K (5930 °C)", d: "19.25 g/cm³", en: 2.36, ox: "+6, +4", yr: 1781, by: "Carl Wilhelm Scheele, Juan and Fausto Elhuyar", uses: ["Highest melting point of all elements (3422 °C)", "Tungsten carbide (WC) heavy-duty industrial cutting and mining drills", "Incandescent light bulb filaments and TIG welding electrodes", "Armor-piercing kinetic penetrator munitions"] },
    { z: 75, s: "Re", n: "Rhenium", m: "186.21 u", g: 7, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d⁵ 6s²", mp: "3459 K (3186 °C)", bp: "5869 K (5596 °C)", d: "21.02 g/cm³", en: 1.9, ox: "+7, +6, +4", yr: 1925, by: "Masataka Ogawa, Walter Noddack, Ida Tacke-Noddack, Otto Berg", uses: ["Single-crystal superalloys for high-temperature commercial jet engine combustion chambers", "Platinum-rhenium unleaded high-octane gasoline reforming catalysts", "Mass spectrometer filament wires", "X-ray tube rotating target anodes"] },
    { z: 76, s: "Os", n: "Osmium", m: "190.23 u", g: 8, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d⁶ 6s²", mp: "3306 K (3033 °C)", bp: "5285 K (5012 °C)", d: "22.59 g/cm³", en: 2.2, ox: "+8, +4, +3", yr: 1803, by: "Smithson Tennant", uses: ["Densest naturally occurring element on Earth (22.59 g/cm³)", "Osmium tetroxide (OsO₄) biological lipid staining for transmission electron microscopy", "Fountain pen tipping alloys and ultra-durable instrument pivots", "Electrical contacts"] },
    { z: 77, s: "Ir", n: "Iridium", m: "192.22 u", g: 9, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d⁷ 6s²", mp: "2719 K (2446 °C)", bp: "4701 K (4428 °C)", d: "22.56 g/cm³", en: 2.20, ox: "+4, +3", yr: 1803, by: "Smithson Tennant", uses: ["Most corrosion-resistant metal known (unaffected by aqua regia at high temperatures)", "High-temperature crucibles for growing single-crystal laser garnets", "Spark plug electrode tips for aircraft and high-performance racing engines", "Geological K-Pg boundary dinosaur extinction marker layer"] },
    { z: 78, s: "Pt", n: "Platinum", m: "195.08 u", g: 10, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d⁹ 6s¹", mp: "2041.4 K (1768.3 °C)", bp: "4098 K (3825 °C)", d: "21.45 g/cm³", en: 2.28, ox: "+4, +2", yr: 1735, by: "Antonio de Ulloa", uses: ["Automotive catalytic converters and hydrogen fuel cell catalysts", "Cisplatin anti-cancer chemotherapy medications", "Corrosion-proof luxury fine jewelry and investment bullion", "Standard International Prototype Kilogram (historic Pt-Ir alloy)"] },
    { z: 79, s: "Au", n: "Gold", m: "196.97 u", g: 11, p: 6, b: "d", c: "transition-metal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", mp: "1337.33 K (1064.18 °C)", bp: "3129 K (2856 °C)", d: "19.30 g/cm³", en: 2.54, ox: "+3, +1", yr: "Ancient", by: "Known to antiquity", uses: ["Global financial monetary reserve standard and luxury jewelry", "Corrosion-free microchip wire bonding and electrical connectors", "Astronaut helmet visor infrared reflective thin-film coatings", "Colloidal gold rapid medical diagnostic test strips"] },
    { z: 80, s: "Hg", n: "Mercury", m: "200.59 u", g: 12, p: 6, b: "d", c: "transition-metal", st: "Liquid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", mp: "234.32 K (-38.83 °C)", bp: "629.88 K (356.73 °C)", d: "13.534 g/cm³", en: 2.00, ox: "+2, +1", yr: "Ancient", by: "Known to antiquity", uses: ["Only metal that is liquid at standard room temperature and pressure", "Fluorescent lighting tubes and mercury vapor streetlights", "Dental amalgam tooth fillings (historic alloy with silver)", "Liquid mirror astronomical telescopes"] },
    { z: 81, s: "Tl", n: "Thallium", m: "204.38 u", g: 13, p: 6, b: "p", c: "post-transition", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", mp: "577 K (304 °C)", bp: "1746 K (1473 °C)", d: "11.85 g/cm³", en: 1.62, ox: "+1, +3", yr: 1861, by: "William Crookes", uses: ["Thallium-201 nuclear medicine cardiac stress scintigraphy scans", "Thallium-doped sodium iodide NaI(Tl) scintillation radiation detectors", "Infrared optical glass lenses", "Low-temperature mercury-thallium liquid thermometer alloys (-58 °C)"] },
    { z: 82, s: "Pb", n: "Lead", m: "207.2 u", g: 14, p: 6, b: "p", c: "post-transition", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", mp: "600.61 K (327.46 °C)", bp: "2022 K (1749 °C)", d: "11.34 g/cm³", en: 1.87, ox: "+4, +2", yr: "Ancient", by: "Known to antiquity", uses: ["Automotive lead-acid 12V starter batteries", "Medical X-ray and gamma radiation protective lead aprons and shielding", "Ammunition and scuba diving ballast weights", "Soundproofing architectural acoustic barriers"] },
    { z: 83, s: "Bi", n: "Bismuth", m: "208.98 u", g: 15, p: 6, b: "p", c: "post-transition", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", mp: "544.7 K (271.4 °C)", bp: "1837 K (1564 °C)", d: "9.78 g/cm³", en: 2.02, ox: "+3", yr: 1753, by: "Claude François Geoffroy", uses: ["Pepto-Bismol (bismuth subsalicylate) gastrointestinal medication", "Non-toxic lead substitute for hunting shot and plumbing solders", "Automatic fire sprinkler low-melting eutectic thermal trigger alloys", "Vibrant iridescent hopper crystal collector specimens"] },
    { z: 84, s: "Po", n: "Polonium", m: "[209] u", g: 16, p: 6, b: "p", c: "post-transition", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", mp: "527 K (254 °C)", bp: "1235 K (962 °C)", d: "9.196 g/cm³", en: 2.0, ox: "+4, +2", yr: 1898, by: "Marie and Pierre Curie", uses: ["High-intensity alpha radiation heat sources for Soviet Lunokhod lunar rovers", "Industrial static eliminator brushes for film and paper manufacturing", "Neutron trigger initiator in early atomic weapons", "Named in honor of Marie Curie's native Poland"] },
    { z: 85, s: "At", n: "Astatine", m: "[210] u", g: 17, p: 6, b: "p", c: "reactive-nonmetal", st: "Solid", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", mp: "575 K (302 °C, est.)", bp: "610 K (337 °C, est.)", d: "Data not available", en: 2.2, ox: "+7, +5, +3, +1, -1", yr: 1940, by: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè", uses: ["Astatine-211 targeted alpha-particle therapy (TAT) for metastatic cancer oncology", "Rarest naturally occurring element in Earth's crust (less than 1 gram present at any moment)", "Short half-life radioisotope halogen", "Fundamental nuclear physics research"] },
    { z: 86, s: "Rn", n: "Radon", m: "[222] u", g: 18, p: 6, b: "p", c: "noble-gas", st: "Gas", cfg: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", mp: "202 K (-71 °C)", bp: "211.3 K (-61.7 °C)", d: "9.73 g/L", en: 2.2, ox: "+2, 0", yr: 1900, by: "Friedrich Ernst Dorn", uses: ["Naturally occurring radioactive decay product of radium and uranium in granite soil", "Second leading cause of lung cancer worldwide after cigarette smoking", "Groundwater hydrological tracking tracer", "Earthquake prediction precursor research"] },
    { z: 87, s: "Fr", n: "Francium", m: "[223] u", g: 1, p: 7, b: "s", c: "alkali-metal", st: "Solid", cfg: "[Rn] 7s¹", mp: "300 K (27 °C, est.)", bp: "950 K (677 °C, est.)", d: "Data not available", en: 0.79, ox: "+1", yr: 1939, by: "Marguerite Perey", uses: ["Laser-cooled magneto-optical atom trapping for atomic structure and parity violation physics", "Second rarest natural element in Earth's crust (approx. 20-30 grams in crust)", "Short half-life (longest-lived Fr-223 is 22 minutes)", "Named after France by discoverer Marguerite Perey"] },
    { z: 88, s: "Ra", n: "Radium", m: "[226] u", g: 2, p: 7, b: "s", c: "alkaline-earth", st: "Solid", cfg: "[Rn] 7s²", mp: "1233 K (960 °C)", bp: "2010 K (1737 °C)", d: "5.5 g/cm³", en: 0.9, ox: "+2", yr: 1898, by: "Marie and Pierre Curie", uses: ["Historic luminescent paint for aircraft gauges and clocks (Radium Girls era)", "Radium-223 (Xofigo) alpha radiation treatment for prostate bone metastases", "Historical radiation therapy for cancer tumors", "Discovery paved the way for nuclear physics"] },
    { z: 89, s: "Ac", n: "Actinium", m: "[227] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 6d¹ 7s²", mp: "1323 K (1050 °C)", bp: "3473 K (3200 °C)", d: "10.07 g/cm³", en: 1.1, ox: "+3", yr: 1899, by: "André-Louis Debierne", uses: ["Actinium-225 groundbreaking targeted alpha therapy (TAT) in precision cancer oncology", "Radioisotope thermoelectric generator heat source", "Intense neutron source when mixed with beryllium", "Glows with an eerie blue light in the dark due to intense ionizing radiation"] },
    { z: 90, s: "Th", n: "Thorium", m: "232.04 u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 6d² 7s²", mp: "2115 K (1842 °C)", bp: "5061 K (4788 °C)", d: "11.72 g/cm³", en: 1.3, ox: "+4", yr: 1829, by: "Jöns Jacob Berzelius", uses: ["Thorium Molten Salt Nuclear Reactors (clean nuclear fission energy)", "Non-radioactive gas camping lantern mantles (Thorium dioxide ThO₂)", "High-temperature refractory welding electrodes (Thoriated tungsten)", "High-index optical camera lenses"] },
    { z: 91, s: "Pa", n: "Protactinium", m: "231.04 u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f² 6d¹ 7s²", mp: "1841 K (1568 °C)", bp: "4300 K (4027 °C)", d: "15.37 g/cm³", en: 1.5, ox: "+5, +4", yr: 1913, by: "Kasimir Fajans, Oswald Helmuth Göhring", uses: ["Oceanographic sediment radiometric dating (Pa-231/Th-230 ratio)", "Intermediary decay product in the thorium nuclear fuel cycle", "Fundamental research on transuranic actinide bonding", "Highly toxic and intensely radioactive heavy metal"] },
    { z: 92, s: "U", n: "Uranium", m: "238.03 u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f³ 6d¹ 7s²", mp: "1405.3 K (1132.2 °C)", bp: "4404 K (4131 °C)", d: "19.1 g/cm³", en: 1.38, ox: "+6, +5, +4, +3", yr: 1789, by: "Martin Heinrich Klaproth", uses: ["Nuclear power plant fuel (Uranium-235 fission generates carbon-free electricity)", "Depleted uranium high-density tank armor and armor-piercing munitions", "Uranium-lead radiometric dating of ancient zircon crystals (determines Earth's age: 4.54 billion yrs)", "Historic canary yellow fluorescent uranium glass"] },
    { z: 93, s: "Np", n: "Neptunium", m: "[237] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f⁴ 6d¹ 7s²", mp: "917 K (644 °C)", bp: "4273 K (4000 °C)", d: "20.45 g/cm³", en: 1.36, ox: "+6, +5, +4, +3", yr: 1940, by: "Edwin McMillan, Philip H. Abelson", uses: ["Precursor for synthesizing Plutonium-238 for NASA deep-space RTG batteries", "First synthetic transuranium element produced in a cyclotron particle accelerator", "High-energy neutron detection sensors", "Nuclear proliferation monitoring research"] },
    { z: 94, s: "Pu", n: "Plutonium", m: "[244] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f⁶ 7s²", mp: "912.5 K (639.4 °C)", bp: "3501 K (3228 °C)", d: "19.86 g/cm³", en: 1.28, ox: "+6, +5, +4, +3", yr: 1940, by: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl", uses: ["Plutonium-238 heat source for NASA Voyager 1 & 2, Curiosity, and Perseverance Mars rovers", "Plutonium-239 fissile nuclear energy and atomic weapon warheads", "Mixed Oxide (MOX) fuel in commercial nuclear power reactors", "Exhibits 6 complex allotropic crystal phases with extreme volume changes"] },
    { z: 95, s: "Am", n: "Americium", m: "[243] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f⁷ 7s²", mp: "1449 K (1176 °C)", bp: "2880 K (2607 °C)", d: "12 g/cm³", en: 1.13, ox: "+6, +5, +4, +3", yr: 1944, by: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso", uses: ["Americium-241 ionization residential smoke detectors (millions in everyday household use)", "Industrial fluid level and metal thickness gauges", "Neutron radiography sources for oil well logging", "Radioisotope thermoelectric space generator research"] },
    { z: 96, s: "Cm", n: "Curium", m: "[247] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f⁷ 6d¹ 7s²", mp: "1613 K (1340 °C)", bp: "3383 K (3110 °C)", d: "13.51 g/cm³", en: 1.28, ox: "+4, +3", yr: 1944, by: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso", uses: ["Alpha Particle X-Ray Spectrometers (APXS) on NASA Mars rovers for geological rock analysis", "Heavy transuranic isotope production in high-flux nuclear reactors", "Heat source for deep-sea and space exploration equipment", "Named in honor of Marie and Pierre Curie"] },
    { z: 97, s: "Bk", n: "Berkelium", m: "[247] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f⁹ 7s²", mp: "1259 K (986 °C)", bp: "2900 K (2627 °C)", d: "14.78 g/cm³", en: 1.3, ox: "+4, +3", yr: 1949, by: "Stanley G. Thompson, Albert Ghiorso, Glenn T. Seaborg", uses: ["Target material for synthesizing element 117 (Tennessine) at the JINR Dubna collider", "Fundamental scientific research on heavy actinide coordination chemistry", "Produced in milligram quantities at Oak Ridge National Laboratory High Flux Isotope Reactor", "Named after the city of Berkeley, California"] },
    { z: 98, s: "Cf", n: "Californium", m: "[251] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹⁰ 7s²", mp: "1173 K (900 °C)", bp: "1743 K (1470 °C)", d: "15.1 g/cm³", en: 1.3, ox: "+3", yr: 1950, by: "Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso, Glenn T. Seaborg", uses: ["Extremely powerful portable spontaneous neutron emitter (1 microgram emits 2.3 million neutrons/sec)", "Neutron moisture gauges for oil well logging and mineral exploration", "Airport security neutron activation luggage explosive detectors", "Reactor startup neutron source"] },
    { z: 99, s: "Es", n: "Einsteinium", m: "[252] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹¹ 7s²", mp: "1133 K (860 °C)", bp: "1269 K (996 °C, est.)", d: "8.84 g/cm³", en: 1.3, ox: "+3", yr: 1952, by: "Albert Ghiorso and team at Berkeley Lab", uses: ["Discovered in the radioactive fallout debris of the first thermonuclear explosion (Ivy Mike, 1952)", "Target material used to synthesize element 101 (Mendelevium)", "Fundamental relativistic actinide quantum chemistry research", "Named in honor of Albert Einstein"] },
    { z: 100, s: "Fm", n: "Fermium", m: "[257] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹² 7s²", mp: "1800 K (1527 °C, est.)", bp: "Data not available", d: "Data not available", en: 1.3, ox: "+3, +2", yr: 1952, by: "Albert Ghiorso and team at Berkeley Lab", uses: ["Discovered in the debris of the Ivy Mike thermonuclear test in the Pacific Ocean", "Heaviest element that can currently be produced by neutron capture in high-flux reactors", "Fundamental nuclear physics research into spontaneous fission", "Named in honor of nuclear pioneer Enrico Fermi"] },
    { z: 101, s: "Md", n: "Mendelevium", m: "[258] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹³ 7s²", mp: "1100 K (827 °C, est.)", bp: "Data not available", d: "Data not available", en: 1.3, ox: "+3, +2", yr: 1955, by: "Albert Ghiorso, Bernard G. Harvey, Gregory R. Choppin, Stanley G. Thompson, Glenn T. Seaborg", uses: ["First element synthesized one atom at a time via particle accelerator bombardment", "Fundamental investigations of actinide valence and oxidation states", "Named in honor of Dmitri Mendeleev, father of the Periodic Table", "No commercial applications due to ultra-short half-life"] },
    { z: 102, s: "No", n: "Nobelium", m: "[259] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹⁴ 7s²", mp: "1100 K (827 °C, est.)", bp: "Data not available", d: "Data not available", en: 1.3, ox: "+3, +2", yr: 1966, by: "Flyorov Laboratory of Nuclear Reactions (Dubna, Russia) & Berkeley Lab", uses: ["Fundamental nuclear structure and decay kinematics research", "Exhibits anomalously stable +2 oxidation state due to filled 5f¹⁴ electronic subshell", "Synthesized via cyclotron ion bombardment of curium targets", "Named in honor of Alfred Nobel, inventor of dynamite and founder of Nobel Prizes"] },
    { z: 103, s: "Lr", n: "Lawrencium", m: "[266] u", g: "f-block", p: 7, b: "f", c: "actinide", st: "Solid", cfg: "[Rn] 5f¹⁴ 7s² 7p¹", mp: "1900 K (1627 °C, est.)", bp: "Data not available", d: "Data not available", en: 1.3, ox: "+3", yr: 1961, by: "Albert Ghiorso, Torbjørn Sikkeland, Almon Larsh, Robert M. Latimer", uses: ["Final member of the actinide series", "Relativistic quantum mechanics effects cause its outer electron to occupy a 7p orbital instead of 6d", "Single-atom chemical gas-phase chromatography experiments", "Named in honor of Ernest O. Lawrence, inventor of the cyclotron"] },
    { z: 104, s: "Rf", n: "Rutherfordium", m: "[267] u", g: 4, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d² 7s²", mp: "2400 K (2100 °C, est.)", bp: "5800 K (5500 °C, est.)", d: "17 g/cm³ (est.)", en: "Data not available", ox: "+4", yr: 1969, by: "Joint Institute for Nuclear Research (Dubna) & Berkeley Lab", uses: ["First transactinide superheavy element (Group 4)", "Single-atom automated gas-phase chemical chromatography research", "Investigating relativistic deviations from regular periodic trends", "Named in honor of Lord Ernest Rutherford, discoverer of the atomic nucleus"] },
    { z: 105, s: "Db", n: "Dubnium", m: "[268] u", g: 5, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d³ 7s²", mp: "Data not available", bp: "Data not available", d: "21.6 g/cm³ (est.)", en: "Data not available", ox: "+5", yr: 1970, by: "JINR (Dubna) & Berkeley Lab", uses: ["Superheavy element Group 5 relativistic transition metal chemistry", "Single-atom halide and oxyhalide volatile complex synthesis", "Synthesized by bombarding Californium-249 with Nitrogen-15 ions", "Named after the science city of Dubna, Russia"] },
    { z: 106, s: "Sg", n: "Seaborgium", m: "[269] u", g: 6, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁴ 7s²", mp: "Data not available", bp: "Data not available", d: "23-24 g/cm³ (est.)", en: "Data not available", ox: "+6", yr: 1974, by: "Lawrence Berkeley Laboratory & LLNL (Albert Ghiorso team)", uses: ["First chemical element named after a living scientist (Glenn T. Seaborg)", "Demonstrated Group 6 chemical behavior forming volatile SgO₂Cl₂ oxychlorides", "Relativistic heavy element bonding research", "Only a few dozen atoms ever synthesized"] },
    { z: 107, s: "Bh", n: "Bohrium", m: "[270] u", g: 7, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁵ 7s²", mp: "Data not available", bp: "Data not available", d: "26-27 g/cm³ (est.)", en: "Data not available", ox: "+7", yr: 1981, by: "GSI Helmholtz Centre for Heavy Ion Research (Darmstadt, Germany)", uses: ["Synthesized via cold fusion reactions bombarding Bismuth-209 with Chromium-54 ions", "Gas-phase thermochromatography experiments confirming volatile BhO₃Cl oxychloride", "Named in honor of Danish quantum physicist Niels Bohr", "Nuclear decay chain physics"] },
    { z: 108, s: "Hs", n: "Hassium", m: "[269] u", g: 8, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁶ 7s²", mp: "Data not available", bp: "Data not available", d: "27-29 g/cm³ (est.)", en: "Data not available", ox: "+8", yr: 1984, by: "GSI Darmstadt (Peter Armbruster, Gottfried Münzenberg)", uses: ["Forms highly volatile tetroxide HsO₄ analogous to osmium tetroxide", "Demonstrated that superheavy elements obey periodic table chemical periodicity", "Synthesized by bombarding Lead-208 with Iron-58 nuclei", "Named after the German state of Hesse (Hassia in Latin)"] },
    { z: 109, s: "Mt", n: "Meitnerium", m: "[278] u", g: 9, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁷ 7s²", mp: "Data not available", bp: "Data not available", d: "27-28 g/cm³ (est.)", en: "Data not available", ox: "+9, +6, +3 (predicted)", yr: 1982, by: "GSI Darmstadt (Peter Armbruster, Gottfried Münzenberg)", uses: ["Named exclusively in honor of Austrian physicist Lise Meitner, discoverer of nuclear fission", "Synthesized by fusing Bismuth-209 and Iron-58 nuclei", "Investigating nuclear island of stability decay paths", "Extremely short half-life (seconds to milliseconds)"] },
    { z: 110, s: "Ds", n: "Darmstadtium", m: "[281] u", g: 10, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁸ 7s²", mp: "Data not available", bp: "Data not available", d: "26-27 g/cm³ (est.)", en: "Data not available", ox: "+6, +4, +2 (predicted)", yr: 1994, by: "GSI Darmstadt (Sigurd Hofmann and team)", uses: ["Synthesized via heavy ion fusion bombarding Lead-208 with Nickel-62 ions", "Superheavy element relativistic electronic configuration research", "Named in honor of the German city of Darmstadt", "High-energy nuclear physics accelerator diagnostics"] },
    { z: 111, s: "Rg", n: "Roentgenium", m: "[282] u", g: 11, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d⁹ 7s²", mp: "Data not available", bp: "Data not available", d: "28.7 g/cm³ (est.)", en: "Data not available", ox: "+5, +3, -1 (predicted)", yr: 1994, by: "GSI Darmstadt (Sigurd Hofmann team)", uses: ["Named in honor of Wilhelm Conrad Röntgen, discoverer of X-rays", "Relativistic contraction of the 7s shell predicted to alter its chemical noble metal properties", "Synthesized by fusing Bismuth-209 with Nickel-64 nuclei", "Produced atom-by-atom in particle accelerators"] },
    { z: 112, s: "Cn", n: "Copernicium", m: "[285] u", g: 12, p: 7, b: "d", c: "transition-metal", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", mp: "283 K (10 °C, est.)", bp: "340 K (67 °C, est.)", d: "14.0 g/cm³ (est.)", en: "Data not available", ox: "+4, +2, 0", yr: 1996, by: "GSI Darmstadt (Sigurd Hofmann team)", uses: ["Relativistic effects make Copernicium extremely volatile; may behave as a noble gas-like liquid or gas", "Adsorption thermochromatography experiments on gold surfaces", "Named in honor of Renaissance astronomer Nicolaus Copernicus", "Heavy ion fusion research"] },
    { z: 113, s: "Nh", n: "Nihonium", m: "[286] u", g: 13, p: 7, b: "p", c: "post-transition", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", mp: "700 K (430 °C, est.)", bp: "1400 K (1130 °C, est.)", d: "16 g/cm³ (est.)", en: "Data not available", ox: "+3, +1 (predicted)", yr: 2004, by: "RIKEN Nishina Center (Kosuke Morita team, Japan)", uses: ["First chemical element officially discovered in an Asian nation (Japan)", "Synthesized by bombarding Bismuth-209 with Zinc-70 ions for over 500 beam days", "Name derived from 'Nihon', the Japanese name for Japan", "Research on heavy p-block electronic shell closures"] },
    { z: 114, s: "Fl", n: "Flerovium", m: "[289] u", g: 14, p: 7, b: "p", c: "post-transition", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", mp: "200 K (-73 °C, est.)", bp: "380 K (107 °C, est.)", d: "9.9 g/cm³ (est.)", en: "Data not available", ox: "+2, 0 (predicted)", yr: 1998, by: "JINR (Dubna, Russia) & LLNL", uses: ["Located near the theoretical 'Island of Stability' for superheavy nuclei", "Strong spin-orbit splitting of the 7p subshell causes Fl to behave almost like a volatile noble metal", "Synthesized by fusing Plutonium-244 with Calcium-48 ions", "Named in honor of Soviet nuclear physicist Georgy Flyorov"] },
    { z: 115, s: "Mc", n: "Moscovium", m: "[290] u", g: 15, p: 7, b: "p", c: "post-transition", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", mp: "670 K (400 °C, est.)", bp: "1400 K (1100 °C, est.)", d: "13.5 g/cm³ (est.)", en: "Data not available", ox: "+3, +1 (predicted)", yr: 2003, by: "JINR (Dubna, Russia), LLNL & ORNL", uses: ["Synthesized via fusion of Americium-243 target with high-intensity Calcium-48 beam", "Alpha decay daughter produces Nihonium isotopes", "Named in honor of the Moscow region (Oblast) where JINR Dubna is situated", "Relativistic atomic physics investigations"] },
    { z: 116, s: "Lv", n: "Livermorium", m: "[293] u", g: 16, p: 7, b: "p", c: "post-transition", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", mp: "709 K (436 °C, est.)", bp: "1085 K (812 °C, est.)", d: "12.9 g/cm³ (est.)", en: "Data not available", ox: "+4, +2 (predicted)", yr: 2000, by: "JINR (Dubna) & Lawrence Livermore National Laboratory (LLNL)", uses: ["Synthesized by bombarding Curium-248 targets with Calcium-48 projectile ions", "Investigation of superheavy nuclear decay chains and fission barriers", "Named in honor of LLNL and the city of Livermore, California", "Chalcogen group superheavy element"] },
    { z: 117, s: "Ts", n: "Tennessine", m: "[294] u", g: 17, p: 7, b: "p", c: "unknown", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", mp: "623-823 K (350-550 °C, est.)", bp: "883 K (610 °C, est.)", d: "7.1-7.3 g/cm³ (est.)", en: "Data not available", ox: "+5, +3, +1, -1 (predicted)", yr: 2010, by: "JINR (Dubna), LLNL, ORNL & Vanderbilt University", uses: ["Synthesized by colliding a rare Berkelium-249 target (from ORNL) with Calcium-48 ions", "Heaviest known halogen-group element; predicted to show metallic metalloid character due to relativistic effects", "Named in honor of the state of Tennessee (Oak Ridge, Vanderbilt, UT)", "Only 15 atoms ever created"] },
    { z: 118, s: "Og", n: "Oganesson", m: "[294] u", g: 18, p: 7, b: "p", c: "unknown", st: "Unknown", cfg: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", mp: "325 K (52 °C, est.)", bp: "450 K (177 °C, est.)", d: "4.9-5.1 g/cm³ (est.)", en: "Data not available", ox: "+4, +2, 0, -1 (predicted)", yr: 2002, by: "JINR (Dubna, Russia) & LLNL", uses: ["Highest atomic number (Z=118) and highest atomic mass of any chemical element currently discovered", "Extreme relativistic spin-orbit effects blur electronic shells into a uniform Fermi electron gas", "Predicted to be a solid semiconductor at room temperature rather than a gas", "Named in honor of Russian nuclear physicist Yuri Oganessian"] }
  ];

  // Merge full specs into ELEMENTS_DATA
  elementsSpecs.forEach(spec => {
    // Generate shells array mathematically & based on electronic configuration
    let shells = [2, 8, 18, 32];
    if (spec.z <= 36) {
      if (spec.z <= 20) shells = [2, 8, spec.z - 10 <= 8 ? spec.z - 10 : 8, spec.z > 18 ? spec.z - 18 : 0].filter(Boolean);
      else shells = [2, 8, 8 + (spec.z - 18 - (spec.cfg.includes("4s¹") ? 1 : 2)), spec.cfg.includes("4s¹") ? 1 : 2];
    } else if (spec.z <= 54) {
      shells = [2, 8, 18, 8 + (spec.z - 36 - (spec.cfg.includes("5s¹") ? 1 : (spec.cfg.includes("5s⁰") || spec.cfg.includes("4d¹⁰") && !spec.cfg.includes("5s") ? 0 : 2))), spec.cfg.includes("5s¹") ? 1 : (spec.cfg.includes("5s²") ? 2 : (spec.z > 48 ? spec.z - 48 : 0))].filter(Boolean);
    } else if (spec.z <= 86) {
      shells = [2, 8, 18, 32, spec.z >= 72 ? 8 + (spec.z - 71) : 18, spec.z >= 81 ? spec.z - 80 : 2].filter(Boolean);
    } else {
      shells = [2, 8, 18, 32, 32, spec.z >= 104 ? 8 + (spec.z - 103) : 18, spec.z >= 113 ? spec.z - 112 : 2].filter(Boolean);
    }

    const neutrons = parseInt(spec.m.replace(/[^\d]/g, ""), 10) - spec.z;

    ELEMENTS_DATA.push({
      atomicNumber: spec.z,
      symbol: spec.s,
      name: spec.n,
      atomicMass: spec.m,
      electronicConfiguration: spec.cfg,
      electronShells: shells,
      valenceElectrons: spec.g === "f-block" ? "Variable" : (spec.z >= 104 ? "Predicted" : (spec.g > 12 ? spec.g - 10 : (spec.g <= 2 ? spec.g : "Variable"))),
      group: spec.g,
      period: spec.p,
      block: spec.b,
      category: spec.c,
      state: spec.st,
      protons: spec.z,
      neutrons: isNaN(neutrons) ? "Variable" : neutrons,
      electrons: spec.z,
      meltingPoint: spec.mp,
      boilingPoint: spec.bp,
      density: spec.d,
      electronegativity: spec.en,
      oxidationStates: spec.ox,
      discoveryYear: spec.yr,
      discoveredBy: spec.by,
      phaseAtRoomTemperature: spec.st === "Unknown" ? "Expected Solid" : spec.st,
      commonUses: spec.uses,
      funFacts: [
        `${spec.n} (${spec.s}, Z=${spec.z}) belongs to ${spec.g === "f-block" ? "the " + spec.c + " series" : "Group " + spec.g + " and Period " + spec.p}.`,
        spec.uses[0]
      ],
      dataSource: "IUPAC / NIST Reference",
      dataNotes: spec.st === "Unknown" ? "Synthetic superheavy element. Physical constants are predicted/calculated due to microsecond half-lives." : "Standard authoritative chemical constants."
    });
  });
})();

// Freeze dataset for integrity
Object.freeze(ELEMENTS_DATA);
